### ISSUE TITLE
Run masternode

### ISSUE THREAD

**Issue by deadblackclover** [BEAR-COIN/bear-core#1]
Hello! I really like your coins, but unfortunately I have not found instructions on how to start a masternode. How can i do this?

**Comment by VoytekMich** [comment]
Procedure is quite simple, please join our [Discord](https://bearcoin.net/go/discord)

In section "Community(Public)->Support" you will find answer. In case additional questions we can help you via [Discord](https://bearcoin.net/go/discord).

**Comment by deadblackclover** [comment]
Unfortunately, I don't use Discord. Is it possible to know how to raise a masternode without this?

**Comment by VoytekMich** [comment]
Sorry for delay. We are preparing also masternodes manager/installation script. Probably tutorial and script will be published on github tomorrow.

**Comment by VoytekMich** [comment]
BEAR Coin Masternode Guide is here: https://github.com/BEAR-COIN/masternodes/blob/master/README.md
